# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-30 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_admin', '0002_auto_20190330_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubadmin',
            name='token',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
