# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-25 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$36000$MnH0ABjGtfQd$OF+Yh/NgzDARMwvzQD5wWr5LY++7sXKchat5DM6qCNM=', max_length=256),
        ),
    ]
