# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-26 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20190325_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$36000$nbyAkOa7TDIu$hOhHWygDpdCm1Qopi0uRUVGamhLN5tbS2YQrGzj6iuc=', max_length=256),
        ),
    ]
