# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-29 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20190326_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$36000$ROfxriNa2WBj$LHCSbzReurcyep0gFheMJ2PvhIAtJ55zPQTbMJN+nNE=', max_length=256),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='qq',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
