# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-30 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20190330_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$36000$8NDxQJBgGSAy$SLBlppC61GUg2YqR6fkCjDtAgAupXDt9GeP6IwHYu60=', max_length=256),
        ),
    ]
