# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-30 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_auto_20190330_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$36000$fCeiEbG1Aok2$fEmo0jtuNO/gS6c9ZhKhfWXqk6L0yoYtjCpgqvDTGUI=', max_length=256),
        ),
    ]
